<?php

namespace anun\CmsBundle\Repository;

/**
 * ItemGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
