imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@anunWebBundle/Resources/config/services.yml" }
    - { resource: "@anunCmsBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.category_images: /uploads/images/categories
    app.path.item_images: /uploads/images/items
    image_path_item: /uploads/images/items
    image_path_category: /uploads/images/categories
    image_path_project: /uploads/images/projects

assetic:
    bundles:        [ 'XmonColorPickerTypeBundle' ]

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
          image_path_item: /uploads/images/items
          image_path_category: /uploads/images/categories
          image_path_project: /uploads/images/projects
    form:
            resources:
                - 'XmonColorPickerTypeBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: anun\CmsBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

vich_uploader:
    db_driver: orm
    mappings:
        category_images:
            uri_prefix: '%app.path.category_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/categories'
        item_images:
            uri_prefix: '%app.path.item_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/items'

        project_images:
            uri_prefix: "%image_path_project%"
            upload_destination: "%kernel.root_dir%/../web/uploads/images/projects"

ivory_ck_editor:
    input_sync: true
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []

        long:
            height: "1000px"
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []

fm_elfinder:
#    assets_path: /uploads # default is /assets, this is where css/js elfinder files are
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            #editor_template: custom template for your editor # default null
            #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            #fullscreen: true|false # default is true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            include_assets: true # disable if you want to manage loading of javascript and css assets manually
            #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                debug: true # defaults to false
                roots:       # at least one root must be defined, defines root filemanager directories
                    uploads:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini

easy_admin:
    site_name: 'АНУН CMS'
    design:
        brand_color: '#ddb707'
        assets:
            js:
                - 'bundles/xmoncolorpickertype/js/jscolor.js'
    formats:
        date:     'Y/m/d'
        time:     'H:i'
        datetime: 'Y/m/d H:i:s'
    entities:
        User:
            class: anun\CmsBundle\Entity\User
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
        Item:
            class: anun\CmsBundle\Entity\Item
            label: 'Тавилга'
            list:
               title: 'Тавилгын жагсаалт'
               fields:
                  - id
                  - { property: 'category' }
                  - { property: 'name', label: 'Нэр' }
                  - { property: 'serialCode', label: 'Барааны код' }
                  - { property: 'main_img_path', label: 'Зураг', type: 'image', base_path: '%app.path.item_images%'}
                  - { property: 'href', label: 'Үсрэх URL'}
                  - { property: 'href_target', label: 'Шинэ таб', type: 'boolean'}
                  - { property: 'publish_at', type: 'datetime' }
                  - { property: 'expire_at', type: 'datetime' }
                  - { property: 'created_at', type: 'datetime' }
                  - { property: 'updated_at', type: 'datetime' }
                  - order_num
            max_results: 50
            form:
                title: 'Тавилга нэмэх/засах'
                fields:
                    - { property: 'category', type: 'entity', type_options: {class: 'anun\CmsBundle\Entity\ItemCategory', property: 'name'} }
                    - name
                    - href
                    - { property: 'serialCode', label: 'Барааны код'}
                    - { property: 'colors', type: 'collection', type_options: { entry_type: 'anun\CmsBundle\Form\ItemColorType', by_reference: false }}
                    - { property: 'href_target', type: 'checkbox' }
                    - { property: 'mainImgFile',label: 'Нүүр зураг', type: 'vich_image',, type_options: { required: false }  }
                    - { property: 'headline', type: 'ckeditor', label: 'Тайлбар'}
                    - { property: 'content', type: 'ckeditor' , label: 'Арчлах заавар'}
                    - { property: 'description', type: 'ckeditor' , label: 'Бүтээгдэхүүний хэмжээ'}
                    - { property: 'publish_at', type: 'datetime'}
                    - { property: 'expire_at', type: 'datetime'}
                    - { property: 'images', type: 'collection', type_options: { entry_type: 'anun\CmsBundle\Form\ItemGalleryType', by_reference: false,required: false } }
                    - { property: 'order_num', type: 'integer' }
        ItemCategory:
           class: anun\CmsBundle\Entity\ItemCategory
           max_results: 50
           label: 'Категори'
           list:
               dql_filter: 'entity.parent is not null'
               sort: 'orderNum'
               title: 'Категорийн жагсаалт'
               fields:
                  - id
                  - { property: 'parent' }
                  - name
                  - { property: 'uildverlel', label: 'Үйлдвэрлэл'}
                  - { property: 'img_path', label: 'Зураг', type: 'image', base_path: '%app.path.category_images%' }
                  - { property: 'created_at', type: 'datetime' }
                  - { property: 'updated_at', type: 'datetime' }
                  - order_num
                  - { property: 'items', label: 'Тавилгын тоо' }
           form:
              title: 'Категори нэмэх/засах'
              fields:
                  - name
                  - { property: parent, type: 'entity', type_options: {class: 'anun\CmsBundle\Entity\ItemCategory', property: 'name',empty_value: '', required: true}}
                  - { property: descr,  type: 'ckeditor'}
                  - { property: 'uildverlel', label: 'Үйлдвэрлэл', type: "checkbox"}
                  - { property: 'imgFile', label: 'Зураг', type: 'vich_image' ,type_options: { required: false }  }
                  - { property: order_num, type: 'integer' }
        ItemGallery:
            class: anun\CmsBundle\Entity\ItemGallery
            list:
                title: 'Зургийн сан'
                fields:
                    - id
                    - { property: 'img_path', label: 'Зураг', type: 'image', base_path: '%app.path.item_images%' }
                    - { property: 'created_at', type: 'datetime'}
                    - order_num
                    - size
            form:
                fields:
                    - { property: 'imgFile', label: 'Зураг', type: 'vich_image' }

        Project:
            class: anun\CmsBundle\Entity\Project
            list:
                title: 'Төслүүд'
                fields:
                    - title
                    - headline
                    - { property: 'previewImg', type: 'image', base_path: '%image_path_project%' }
                    - client
                    - detailSize
                    - detailYear
                    - detailLocation
                    - detailGoods

            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Төслийн агуулга'}
                    - { property: body,  type: 'ckeditor', type_options: {config_name: "long"} }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Дэлгэрэнгүй мэдээлэл'}
                    - title
                    - headline
                    - { property: 'previewImgFile', label: 'Зураг', type: 'vich_image' ,type_options: { required: false }  }
                    - client
                    - detailSize
                    - detailYear
                    - detailLocation
                    - detailGoods
