easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

anun_web:
    resource: "@anunWebBundle/Controller/"
    type:     annotation
    prefix:   /

